Improve error handling in use and revdep snippets.

diff --git a/templates/revdep-snippet b/templates/revdep-snippet
--- a/templates/revdep-snippet
+++ b/templates/revdep-snippet
@@ -1,4 +1,13 @@
-if @@FEATURES@@ @@USE@@ emerge -1 @@EMERGEOPTS@@ @@CPV@@; then
-echo "@@FEATURES@@ @@USE@@ emerge -1 @@EMERGEOPTS@@ @@CPV@@ succeeded" >> @@REPORTFILE@@;
-else echo "@@FEATURES@@ @@USE@@  emerge -1 @@EMERGEOPTS@@ @@CPV@@ failed" >> @@REPORTFILE@@;
+eout=$( @@FEATURES@@  @@USE@@ emerge -1 @@EMERGEOPTS@@ @@CPV@@ 2>&1 1>/dev/tty )
+if [[ $? == 0 ]] ; then
+  echo "@@FEATURES@@ @@USE@@ succeeded for @@CPV@@" >> @@REPORTFILE@@;
+elif [[ "${eout}" =~ REQUIRED_USE ]] ; then
+  echo "${eout}";
+  echo "@@CPV@@ : REQUIRED_USE not satisfied (probably) for " >> @@REPORTFILE@@;
+elif [[ "${eout}" =~ USE_CHANGES ]] ; then
+  echo "${eout}";
+  echo "@@CPV@@ : USE dependencies not satisfied (probably)" >> @@REPORTFILE@@;
+else
+  echo "${eout}";
+  echo "@@FEATURES@@ failed for @@CPV@@" >> @@REPORTFILE@@;
 fi;
